/**
 * Currency Definitions
 *
 * Full ISO 4217 currency list, sorted alphabetically by code.
 * Each entry includes code, symbol, human-readable name, and minor-unit exponent.
 */

export interface CurrencyDefinition {
    code: string;
    symbol: string;
    name: string;
    /**
     * Number of digits in the currency's minor unit: 1 major unit = 10^decimals
     * minor units. 0 (e.g. JPY, XOF), 2 (most), or 3 (e.g. KWD, BHD).
     */
    decimals: number;
}

export const SUPPORTED_CURRENCIES: CurrencyDefinition[] = [
    { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham', decimals: 2 },
    { code: 'AFN', symbol: '؋', name: 'Afghan Afghani', decimals: 2 },
    { code: 'ALL', symbol: 'L', name: 'Albanian Lek', decimals: 2 },
    { code: 'AMD', symbol: '֏', name: 'Armenian Dram', decimals: 2 },
    { code: 'ANG', symbol: 'ƒ', name: 'Netherlands Antillean Guilder', decimals: 2 },
    { code: 'AOA', symbol: 'Kz', name: 'Angolan Kwanza', decimals: 2 },
    { code: 'ARS', symbol: 'AR$', name: 'Argentine Peso', decimals: 2 },
    { code: 'AUD', symbol: 'A$', name: 'Australian Dollar', decimals: 2 },
    { code: 'AWG', symbol: 'ƒ', name: 'Aruban Florin', decimals: 2 },
    { code: 'AZN', symbol: '₼', name: 'Azerbaijani Manat', decimals: 2 },
    { code: 'BAM', symbol: 'KM', name: 'Bosnia-Herzegovina Mark', decimals: 2 },
    { code: 'BBD', symbol: 'Bds$', name: 'Barbadian Dollar', decimals: 2 },
    { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka', decimals: 2 },
    { code: 'BGN', symbol: 'лв', name: 'Bulgarian Lev', decimals: 2 },
    { code: 'BHD', symbol: '.د.ب', name: 'Bahraini Dinar', decimals: 3 },
    { code: 'BIF', symbol: 'FBu', name: 'Burundian Franc', decimals: 0 },
    { code: 'BMD', symbol: 'BD$', name: 'Bermudian Dollar', decimals: 2 },
    { code: 'BND', symbol: 'B$', name: 'Brunei Dollar', decimals: 2 },
    { code: 'BOB', symbol: 'Bs.', name: 'Bolivian Boliviano', decimals: 2 },
    { code: 'BRL', symbol: 'R$', name: 'Brazilian Real', decimals: 2 },
    { code: 'BSD', symbol: 'B$', name: 'Bahamian Dollar', decimals: 2 },
    { code: 'BTN', symbol: 'Nu.', name: 'Bhutanese Ngultrum', decimals: 2 },
    { code: 'BWP', symbol: 'P', name: 'Botswanan Pula', decimals: 2 },
    { code: 'BYN', symbol: 'Br', name: 'Belarusian Ruble', decimals: 2 },
    { code: 'BZD', symbol: 'BZ$', name: 'Belize Dollar', decimals: 2 },
    { code: 'CAD', symbol: 'CA$', name: 'Canadian Dollar', decimals: 2 },
    { code: 'CDF', symbol: 'FC', name: 'Congolese Franc', decimals: 2 },
    { code: 'CHF', symbol: 'CHF', name: 'Swiss Franc', decimals: 2 },
    { code: 'CLP', symbol: 'CL$', name: 'Chilean Peso', decimals: 0 },
    { code: 'CNY', symbol: '¥', name: 'Chinese Yuan', decimals: 2 },
    { code: 'COP', symbol: 'CO$', name: 'Colombian Peso', decimals: 2 },
    { code: 'CRC', symbol: '₡', name: 'Costa Rican Colón', decimals: 2 },
    { code: 'CUP', symbol: '₱', name: 'Cuban Peso', decimals: 2 },
    { code: 'CVE', symbol: 'Esc', name: 'Cape Verdean Escudo', decimals: 2 },
    { code: 'CZK', symbol: 'Kč', name: 'Czech Koruna', decimals: 2 },
    { code: 'DJF', symbol: 'Fdj', name: 'Djiboutian Franc', decimals: 0 },
    { code: 'DKK', symbol: 'kr', name: 'Danish Krone', decimals: 2 },
    { code: 'DOP', symbol: 'RD$', name: 'Dominican Peso', decimals: 2 },
    { code: 'DZD', symbol: 'د.ج', name: 'Algerian Dinar', decimals: 2 },
    { code: 'EGP', symbol: 'E£', name: 'Egyptian Pound', decimals: 2 },
    { code: 'ERN', symbol: 'Nfk', name: 'Eritrean Nakfa', decimals: 2 },
    { code: 'ETB', symbol: 'Br', name: 'Ethiopian Birr', decimals: 2 },
    { code: 'EUR', symbol: '€', name: 'Euro', decimals: 2 },
    { code: 'FJD', symbol: 'FJ$', name: 'Fijian Dollar', decimals: 2 },
    { code: 'FKP', symbol: 'FK£', name: 'Falkland Islands Pound', decimals: 2 },
    { code: 'GBP', symbol: '£', name: 'British Pound', decimals: 2 },
    { code: 'GEL', symbol: '₾', name: 'Georgian Lari', decimals: 2 },
    { code: 'GHS', symbol: 'GH₵', name: 'Ghanaian Cedi', decimals: 2 },
    { code: 'GIP', symbol: '£', name: 'Gibraltar Pound', decimals: 2 },
    { code: 'GMD', symbol: 'D', name: 'Gambian Dalasi', decimals: 2 },
    { code: 'GNF', symbol: 'FG', name: 'Guinean Franc', decimals: 0 },
    { code: 'GTQ', symbol: 'Q', name: 'Guatemalan Quetzal', decimals: 2 },
    { code: 'GYD', symbol: 'G$', name: 'Guyanese Dollar', decimals: 2 },
    { code: 'HKD', symbol: 'HK$', name: 'Hong Kong Dollar', decimals: 2 },
    { code: 'HNL', symbol: 'L', name: 'Honduran Lempira', decimals: 2 },
    { code: 'HRK', symbol: 'kn', name: 'Croatian Kuna', decimals: 2 },
    { code: 'HTG', symbol: 'G', name: 'Haitian Gourde', decimals: 2 },
    { code: 'HUF', symbol: 'Ft', name: 'Hungarian Forint', decimals: 2 },
    { code: 'IDR', symbol: 'Rp', name: 'Indonesian Rupiah', decimals: 2 },
    { code: 'ILS', symbol: '₪', name: 'Israeli Shekel', decimals: 2 },
    { code: 'INR', symbol: '₹', name: 'Indian Rupee', decimals: 2 },
    { code: 'IQD', symbol: 'ع.د', name: 'Iraqi Dinar', decimals: 3 },
    { code: 'IRR', symbol: '﷼', name: 'Iranian Rial', decimals: 2 },
    { code: 'ISK', symbol: 'kr', name: 'Icelandic Króna', decimals: 0 },
    { code: 'JMD', symbol: 'J$', name: 'Jamaican Dollar', decimals: 2 },
    { code: 'JOD', symbol: 'JD', name: 'Jordanian Dinar', decimals: 3 },
    { code: 'JPY', symbol: '¥', name: 'Japanese Yen', decimals: 0 },
    { code: 'KES', symbol: 'KSh', name: 'Kenyan Shilling', decimals: 2 },
    { code: 'KGS', symbol: 'сом', name: 'Kyrgyzstani Som', decimals: 2 },
    { code: 'KHR', symbol: '៛', name: 'Cambodian Riel', decimals: 2 },
    { code: 'KMF', symbol: 'CF', name: 'Comorian Franc', decimals: 0 },
    { code: 'KPW', symbol: '₩', name: 'North Korean Won', decimals: 2 },
    { code: 'KRW', symbol: '₩', name: 'South Korean Won', decimals: 0 },
    { code: 'KWD', symbol: 'د.ك', name: 'Kuwaiti Dinar', decimals: 3 },
    { code: 'KYD', symbol: 'CI$', name: 'Cayman Islands Dollar', decimals: 2 },
    { code: 'KZT', symbol: '₸', name: 'Kazakhstani Tenge', decimals: 2 },
    { code: 'LAK', symbol: '₭', name: 'Laotian Kip', decimals: 2 },
    { code: 'LBP', symbol: 'L£', name: 'Lebanese Pound', decimals: 2 },
    { code: 'LKR', symbol: 'Rs', name: 'Sri Lankan Rupee', decimals: 2 },
    { code: 'LRD', symbol: 'L$', name: 'Liberian Dollar', decimals: 2 },
    { code: 'LSL', symbol: 'M', name: 'Lesotho Loti', decimals: 2 },
    { code: 'LYD', symbol: 'LD', name: 'Libyan Dinar', decimals: 3 },
    { code: 'MAD', symbol: 'MAD', name: 'Moroccan Dirham', decimals: 2 },
    { code: 'MDL', symbol: 'L', name: 'Moldovan Leu', decimals: 2 },
    { code: 'MGA', symbol: 'Ar', name: 'Malagasy Ariary', decimals: 2 },
    { code: 'MKD', symbol: 'ден', name: 'Macedonian Denar', decimals: 2 },
    { code: 'MMK', symbol: 'K', name: 'Myanmar Kyat', decimals: 2 },
    { code: 'MNT', symbol: '₮', name: 'Mongolian Tugrik', decimals: 2 },
    { code: 'MOP', symbol: 'MOP$', name: 'Macanese Pataca', decimals: 2 },
    { code: 'MRU', symbol: 'UM', name: 'Mauritanian Ouguiya', decimals: 2 },
    { code: 'MUR', symbol: '₨', name: 'Mauritian Rupee', decimals: 2 },
    { code: 'MVR', symbol: 'Rf', name: 'Maldivian Rufiyaa', decimals: 2 },
    { code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha', decimals: 2 },
    { code: 'MXN', symbol: 'MX$', name: 'Mexican Peso', decimals: 2 },
    { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit', decimals: 2 },
    { code: 'MZN', symbol: 'MT', name: 'Mozambican Metical', decimals: 2 },
    { code: 'NAD', symbol: 'N$', name: 'Namibian Dollar', decimals: 2 },
    { code: 'NGN', symbol: '₦', name: 'Nigerian Naira', decimals: 2 },
    { code: 'NIO', symbol: 'C$', name: 'Nicaraguan Córdoba', decimals: 2 },
    { code: 'NOK', symbol: 'kr', name: 'Norwegian Krone', decimals: 2 },
    { code: 'NPR', symbol: 'NRs', name: 'Nepalese Rupee', decimals: 2 },
    { code: 'NZD', symbol: 'NZ$', name: 'New Zealand Dollar', decimals: 2 },
    { code: 'OMR', symbol: 'ر.ع.', name: 'Omani Rial', decimals: 3 },
    { code: 'PAB', symbol: 'B/.', name: 'Panamanian Balboa', decimals: 2 },
    { code: 'PEN', symbol: 'S/.', name: 'Peruvian Sol', decimals: 2 },
    { code: 'PGK', symbol: 'K', name: 'Papua New Guinean Kina', decimals: 2 },
    { code: 'PHP', symbol: '₱', name: 'Philippine Peso', decimals: 2 },
    { code: 'PKR', symbol: '₨', name: 'Pakistani Rupee', decimals: 2 },
    { code: 'PLN', symbol: 'zł', name: 'Polish Zloty', decimals: 2 },
    { code: 'PYG', symbol: '₲', name: 'Paraguayan Guarani', decimals: 0 },
    { code: 'QAR', symbol: 'QR', name: 'Qatari Riyal', decimals: 2 },
    { code: 'RON', symbol: 'lei', name: 'Romanian Leu', decimals: 2 },
    { code: 'RSD', symbol: 'din.', name: 'Serbian Dinar', decimals: 2 },
    { code: 'RUB', symbol: '₽', name: 'Russian Ruble', decimals: 2 },
    { code: 'RWF', symbol: 'RF', name: 'Rwandan Franc', decimals: 0 },
    { code: 'SAR', symbol: 'SR', name: 'Saudi Riyal', decimals: 2 },
    { code: 'SBD', symbol: 'SI$', name: 'Solomon Islands Dollar', decimals: 2 },
    { code: 'SCR', symbol: 'SRe', name: 'Seychellois Rupee', decimals: 2 },
    { code: 'SDG', symbol: 'LS', name: 'Sudanese Pound', decimals: 2 },
    { code: 'SEK', symbol: 'kr', name: 'Swedish Krona', decimals: 2 },
    { code: 'SGD', symbol: 'S$', name: 'Singapore Dollar', decimals: 2 },
    { code: 'SHP', symbol: '£', name: 'Saint Helena Pound', decimals: 2 },
    { code: 'SLL', symbol: 'Le', name: 'Sierra Leonean Leone', decimals: 2 },
    { code: 'SOS', symbol: 'Sh', name: 'Somali Shilling', decimals: 2 },
    { code: 'SRD', symbol: 'Sr$', name: 'Surinamese Dollar', decimals: 2 },
    { code: 'SSP', symbol: 'SS£', name: 'South Sudanese Pound', decimals: 2 },
    { code: 'STN', symbol: 'Db', name: 'São Tomé and Príncipe Dobra', decimals: 2 },
    { code: 'SYP', symbol: '£S', name: 'Syrian Pound', decimals: 2 },
    { code: 'SZL', symbol: 'E', name: 'Swazi Lilangeni', decimals: 2 },
    { code: 'THB', symbol: '฿', name: 'Thai Baht', decimals: 2 },
    { code: 'TJS', symbol: 'SM', name: 'Tajikistani Somoni', decimals: 2 },
    { code: 'TMT', symbol: 'T', name: 'Turkmenistani Manat', decimals: 2 },
    { code: 'TND', symbol: 'DT', name: 'Tunisian Dinar', decimals: 3 },
    { code: 'TOP', symbol: 'T$', name: 'Tongan Paʻanga', decimals: 2 },
    { code: 'TRY', symbol: '₺', name: 'Turkish Lira', decimals: 2 },
    { code: 'TTD', symbol: 'TT$', name: 'Trinidad and Tobago Dollar', decimals: 2 },
    { code: 'TWD', symbol: 'NT$', name: 'New Taiwan Dollar', decimals: 2 },
    { code: 'TZS', symbol: 'TSh', name: 'Tanzanian Shilling', decimals: 2 },
    { code: 'UAH', symbol: '₴', name: 'Ukrainian Hryvnia', decimals: 2 },
    { code: 'UGX', symbol: 'USh', name: 'Ugandan Shilling', decimals: 0 },
    { code: 'USD', symbol: '$', name: 'US Dollar', decimals: 2 },
    { code: 'UYU', symbol: '$U', name: 'Uruguayan Peso', decimals: 2 },
    { code: 'UZS', symbol: 'сўм', name: 'Uzbekistani Som', decimals: 2 },
    { code: 'VES', symbol: 'Bs.S', name: 'Venezuelan Bolívar', decimals: 2 },
    { code: 'VND', symbol: '₫', name: 'Vietnamese Dong', decimals: 0 },
    { code: 'VUV', symbol: 'VT', name: 'Vanuatu Vatu', decimals: 0 },
    { code: 'WST', symbol: 'WS$', name: 'Samoan Tala', decimals: 2 },
    { code: 'XAF', symbol: 'FCFA', name: 'Central African CFA Franc', decimals: 0 },
    { code: 'XCD', symbol: 'EC$', name: 'East Caribbean Dollar', decimals: 2 },
    { code: 'XOF', symbol: 'CFA', name: 'West African CFA Franc', decimals: 0 },
    { code: 'XPF', symbol: '₣', name: 'CFP Franc', decimals: 0 },
    { code: 'YER', symbol: '﷼', name: 'Yemeni Rial', decimals: 2 },
    { code: 'ZAR', symbol: 'R', name: 'South African Rand', decimals: 2 },
    { code: 'ZMW', symbol: 'ZK', name: 'Zambian Kwacha', decimals: 2 },
    { code: 'ZWL', symbol: 'Z$', name: 'Zimbabwean Dollar', decimals: 2 },
];

/** Default currency code */
export const DEFAULT_CURRENCY_CODE = 'USD';

/**
 * Get a currency definition by code.
 * Returns USD if code is not found.
 */
export function getCurrencyByCode(code: string): CurrencyDefinition {
    return SUPPORTED_CURRENCIES.find(c => c.code === code)
        ?? SUPPORTED_CURRENCIES.find(c => c.code === 'USD')!;
}
