/**
 * V-114, V-103, V-118: a rule's end is the number of its last occurrence,
 * fixed when the end date is chosen (REGISTRE V-114, V-103, V-118; Owner
 * decisions 1 to 4 of 01/10, pass 71).
 *
 *  - Decision 1 (V-114): what is due on or before the end is generated by the
 *    engine, even after the end day; a rule that cannot generate it shows its
 *    fault, not "Ended".
 *  - Decision 2 (V-103): the last occurrence is fixed by its number when the
 *    end date is chosen; a zone change no longer changes how many there are.
 *  - Decision 3 (V-118): an edit of a rule whose wallet or category is missing
 *    that places the end before a pending occurrence is refused and names the
 *    reason; otherwise the pending occurrence is generated afterwards with the
 *    repaired values. The same refusal covers an edit that repairs and reopens
 *    an ended rule with an occurrence still pending (Owner answer, 01/10).
 *  - Decision 4 (V-114): reopening an ended rule catches nothing up; the next
 *    occurrence is the first on or after the day of the edit.
 *
 * Every case drives the hook the rules screen calls (or the engine the way the
 * app runs it at launch) over a real SQLite database with the write guard
 * armed.
 *
 * Zones (register policy no. 9): fixtures use the LOCAL Date constructor and
 * the clock is pinned with pinClock, so the suite holds in whatever zone the
 * process runs in; it is run under TZ=UTC, Africa/Lagos and America/New_York.
 * A device moving to another zone is simulated in the stored data: every
 * instant on the rules and their rows is moved by the zone difference, which
 * is how those instants read from the new zone. jest cannot change the
 * process zone, and installZoneClock moves the local getters only while
 * startOfDay calls a local setter. Not proved by this: a real zone switch in
 * ICU or Hermes, a DST change at the moment of the move (the shift is a fixed
 * number of hours), or anything on a device.
 */

import { act, renderHook, waitFor } from '@testing-library/react-native';
import { createTestDb } from '../../../tests/helpers/createTestDb';
import { pinClock, restoreZoneClock } from '../../../tests/helpers/zoneClock';
import { CategoryRepository } from '../../data/repositories/CategoryRepository';
import { RecurringTransactionRepository } from '../../data/repositories/RecurringTransactionRepository';
import { TransactionRepository } from '../../data/repositories/TransactionRepository';
import { WalletRepository } from '../../data/repositories/WalletRepository';
import { processRecurringRules } from '../../data/services/RecurringTransactionEngine';
import type { SqlDatabase } from '../../data/storage/sql/SqlDatabase';
import { CategoryType } from '../../domain/entities/Category';
import {
    RecurrenceFrequency,
    type CreateRecurringTransactionDTO,
    type UpdateRecurringTransactionDTO,
} from '../../domain/entities/RecurringTransaction';
import { TransactionType } from '../../domain/entities/Transaction';
import { WalletType } from '../../domain/entities/Wallet';
import { RecurringRuleStatus, deriveRecurringRuleStatus } from '../../domain/recurring';
// jest.mock below is hoisted above every import, so the hook sees the mocks.
import { useRecurringRules } from '../useRecurringRules';

let mockDb: SqlDatabase;
let mockRecurringRepo: RecurringTransactionRepository;
let mockWalletRepo: WalletRepository;
let mockCategoryRepo: CategoryRepository;
let mockTransactionRepo: TransactionRepository;

jest.mock('../../core/di/container', () => ({
    container: {
        get recurringTransactionRepository() {
            return mockRecurringRepo;
        },
        get walletRepository() {
            return mockWalletRepo;
        },
        get categoryRepository() {
            return mockCategoryRepo;
        },
        get transactionRepository() {
            return mockTransactionRepo;
        },
    },
    getRecurringTransactionRepository: () => mockRecurringRepo,
    getWalletRepository: () => mockWalletRepo,
    getCategoryRepository: () => mockCategoryRepo,
    getTransactionRepository: () => mockTransactionRepo,
    getBudgetRepository: () => undefined,
    getUseCaseDeps: () => ({
        runInTransaction: (work: () => Promise<unknown>) => mockDb.runInTransaction(work),
        transactionRepo: mockTransactionRepo,
        walletRepo: mockWalletRepo,
        categoryRepo: mockCategoryRepo,
        recurringRepo: mockRecurringRepo,
        eventBus: { emit: jest.fn(), emitMultiple: jest.fn() },
    }),
}));

jest.mock('../../core/events/dataEvents', () => ({
    dataEvents: {
        subscribe: () => () => undefined,
        emit: jest.fn(),
        emitMultiple: jest.fn(),
    },
}));

const BANK = 'w-bank';
const CASH = 'w-cash';
const OTHER = 'w-other';
const CATEGORY = 'cat-bills';
const NOTE = 'Rent';
const HOUR_MS = 60 * 60 * 1000;

/** A local wall-clock instant in the process zone. `month` is 1-based. */
function localDate(year: number, month: number, day: number, hours = 12, minutes = 0): Date {
    return new Date(year, month - 1, day, hours, minutes);
}

/** Pin the clock to a local wall-clock instant. `month` is 1-based. */
function pinAt(year: number, month: number, day: number, hours = 12, minutes = 0): void {
    pinClock(localDate(year, month, day, hours, minutes).getTime());
}

const pad = (n: number) => String(n).padStart(2, '0');
const ymd = (d: Date) => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;

interface Row {
    id: string;
    day: string;
    amount: number;
    walletId: string;
    index?: number;
}

/** Every row the rules wrote, oldest first; its day is the local day in the process zone. */
async function ledger(): Promise<Row[]> {
    return (await mockTransactionRepo.getAll())
        .filter((t) => t.note === NOTE)
        .sort((a, b) => a.date.getTime() - b.date.getTime())
        .map((t) => ({
            id: t.id,
            day: ymd(t.date),
            amount: t.amount,
            walletId: t.walletId,
            index: t.recurringOccurrenceIndex,
        }));
}

/** The rows written since `before` was read. */
async function addedSince(before: Row[]): Promise<Row[]> {
    const known = new Set(before.map((r) => r.id));
    return (await ledger()).filter((r) => !known.has(r.id));
}

const days = (rows: Row[]) => rows.map((r) => r.day);

async function balanceOf(walletId: string): Promise<number> {
    return (await mockWalletRepo.getById(walletId))!.balance;
}

function engineDeps() {
    return {
        recurringRepo: mockRecurringRepo,
        transactionRepo: mockTransactionRepo,
        walletRepo: mockWalletRepo,
        categoryRepo: mockCategoryRepo,
        eventBus: { emit: jest.fn(), emitMultiple: jest.fn() },
        runInTransaction: mockDb.runInTransaction.bind(mockDb),
    };
}

/** One engine run, as at launch, after a restore or after a create. */
function engine() {
    return processRecurringRules(engineDeps());
}

/** One engine run that must not fail for any rule. */
async function runEngine() {
    const result = await engine();
    expect(result.errors).toEqual([]);
    return result;
}

/** A monthly expense of 1000 on BANK, created the way the app creates it. */
async function createRule(fields: Partial<CreateRecurringTransactionDTO> & { startDate: Date }): Promise<string> {
    const rule = await mockDb.runInTransaction(() => mockRecurringRepo.create({
        type: TransactionType.EXPENSE,
        amount: 1000,
        walletId: BANK,
        categoryId: CATEGORY,
        description: NOTE,
        frequency: RecurrenceFrequency.MONTHLY,
        interval: 1,
        ...fields,
    }));
    return rule.id;
}

/**
 * The DTO the edit form submits for a rule (RecurringRuleForm.tsx:155-165):
 * every field, and the end date as it stands unless `overrides` changes it.
 */
async function formDto(id: string, overrides: Partial<UpdateRecurringTransactionDTO>): Promise<UpdateRecurringTransactionDTO> {
    const rule = (await mockRecurringRepo.getById(id))!;
    return {
        id,
        type: rule.type,
        amount: rule.amount,
        walletId: rule.walletId,
        categoryId: rule.categoryId,
        description: rule.description,
        frequency: rule.frequency,
        interval: rule.interval,
        endDate: rule.endDate ?? null,
        ...overrides,
    };
}

/** A wallet gone without passing the deletion guard, as a v1 restore leaves it. */
async function orphanWallet(walletId: string): Promise<void> {
    await mockDb.runInTransaction(() => mockDb.execute('DELETE FROM wallets WHERE id = ?', [walletId]));
}

/**
 * The device moves to a zone `hoursEast` hours east of the zone that wrote
 * the data (negative: west). Seen from there, every stored instant reads that
 * many hours later on the wall clock; with the process zone fixed, each
 * instant is moved by the same amount instead. The occurrence numbers are
 * integers and do not move.
 */
async function moveDeviceEast(hoursEast: number): Promise<void> {
    const shift = (iso: unknown) => new Date(new Date(String(iso)).getTime() + hoursEast * HOUR_MS).toISOString();
    const { rows: rules } = await mockDb.execute('SELECT id, start_date, end_date, last_generated_date FROM recurring_rules');
    for (const r of rules) {
        await mockDb.runInTransaction(() => mockDb.execute(
            'UPDATE recurring_rules SET start_date = ?, end_date = ?, last_generated_date = ? WHERE id = ?',
            [shift(r.start_date), r.end_date === null ? null : shift(r.end_date), shift(r.last_generated_date), r.id],
        ));
    }
    const { rows: txs } = await mockDb.execute('SELECT id, date FROM transactions');
    for (const t of txs) {
        await mockDb.runInTransaction(() => mockDb.execute('UPDATE transactions SET date = ? WHERE id = ?', [shift(t.date), t.id]));
    }
}

async function mountHook() {
    const view = renderHook(() => useRecurringRules());
    await waitFor(() => {
        expect(view.result.current.loading).toBe(false);
    });
    return view.result;
}

type HookResult = Awaited<ReturnType<typeof mountHook>>;

/** Submit an edit through the hook; resolves to the saved rule or to the refusal. */
async function editRule(result: HookResult, dto: UpdateRecurringTransactionDTO) {
    let outcome: unknown;
    await act(async () => {
        outcome = await result.current.updateRule(dto).catch((error: unknown) => error);
    });
    return outcome;
}

/** The status the rules screen shows for a rule, once wallets and categories have loaded. */
async function expectCardStatus(result: HookResult, id: string, expected: RecurringRuleStatus) {
    await waitFor(() => {
        expect(result.current.statuses[id]).toBe(expected);
    });
}

/** The status derived from what is stored now, with both references read from the database. */
async function storedStatus(id: string): Promise<RecurringRuleStatus> {
    const rule = (await mockRecurringRepo.getById(id))!;
    return deriveRecurringRuleStatus(
        rule,
        {
            wallet: await mockWalletRepo.getById(rule.walletId),
            category: await mockCategoryRepo.getById(rule.categoryId),
        },
        new Date(),
    );
}

interface Refusal {
    name?: string;
    missing?: unknown;
    dueDates?: Date[];
}

beforeEach(async () => {
    mockDb = await createTestDb({ writeGuard: true });
    mockRecurringRepo = new RecurringTransactionRepository(mockDb);
    mockWalletRepo = new WalletRepository(mockDb);
    mockCategoryRepo = new CategoryRepository(mockDb);
    mockTransactionRepo = new TransactionRepository(mockDb);

    await mockDb.runInTransaction(() => mockWalletRepo.save({ id: BANK, name: 'Bank', balance: 10000000, type: WalletType.BANK, createdAt: new Date(2025, 0, 1) }));
    // Cash is guarded by the funds check; 1500 covers 15 Sep and leaves 500,
    // short of the 1000 due on 15 Oct.
    await mockDb.runInTransaction(() => mockWalletRepo.save({ id: CASH, name: 'Cash', balance: 1500, type: WalletType.CASH, createdAt: new Date(2025, 0, 1) }));
    await mockDb.runInTransaction(() => mockWalletRepo.save({ id: OTHER, name: 'Other', balance: 10000000, type: WalletType.BANK, createdAt: new Date(2025, 0, 1) }));
    await mockDb.runInTransaction(() => mockCategoryRepo.save({ id: CATEGORY, name: 'Bills', type: CategoryType.EXPENSE }));
});

afterEach(() => {
    restoreZoneClock();
});

describe('V-114 an ended rule generates what was due before its end (process zone; run under TZ=UTC, Africa/Lagos, America/New_York)', () => {
    it('V-114 a. monthly rule ended yesterday with 15 Oct due and not generated: the engine generates 15 Oct once and debits the wallet once', async () => {
        pinAt(2026, 9, 15, 10, 0);
        await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();
        const before = await ledger();
        const balance = await balanceOf(BANK);

        pinAt(2026, 10, 20, 10, 0);
        await runEngine();
        await runEngine();

        const added = await addedSince(before);
        expect(added.map((r) => [r.day, r.index, r.amount])).toEqual([['2026-10-15', 1, 1000]]);
        expect(await balanceOf(BANK)).toBe(balance - 1000);
    });

    it('V-114 b. a rule created back-dated with its end already passed generates its occurrences up to its end', async () => {
        pinAt(2026, 10, 20);
        const result = await mountHook();
        await act(async () => {
            await result.current.createRule({
                type: TransactionType.EXPENSE,
                amount: 1000,
                walletId: BANK,
                categoryId: CATEGORY,
                description: NOTE,
                startDate: localDate(2026, 7, 15),
                endDate: localDate(2026, 10, 1),
                frequency: RecurrenceFrequency.MONTHLY,
                interval: 1,
            });
        });
        // As RecurringRulesScreen.tsx:318 runs it after a create.
        await runEngine();

        expect(days(await ledger())).toEqual(['2026-07-15', '2026-08-15', '2026-09-15']);
    });

    it('V-114 c. funds: an ended rule whose pending 15 Oct the cash wallet cannot cover is reported INSUFFICIENT_FUNDS, not EXPIRED', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ walletId: CASH, startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();

        pinAt(2026, 10, 20, 10, 0);
        const run = await runEngine();
        expect(run.skipped.map((s) => s.ruleId)).toEqual([id]);

        const result = await mountHook();
        await expectCardStatus(result, id, RecurringRuleStatus.INSUFFICIENT_FUNDS);
    });

    it('V-114 c. missing reference: an ended rule whose wallet is gone with 15 Oct pending is reported MISSING_REFERENCE, not EXPIRED', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();
        await orphanWallet(BANK);

        pinAt(2026, 10, 20, 10, 0);
        const run = await engine();
        expect(run.errors.map((e) => e.ruleId)).toEqual([id]);

        const result = await mountHook();
        await expectCardStatus(result, id, RecurringRuleStatus.MISSING_REFERENCE);
    });
});

describe('V-103 the last occurrence does not move with the zone (process zone; run under TZ=UTC, Africa/Lagos, America/New_York)', () => {
    it('V-103 a. rule C written 6 h east (Paris -> New York shape), read on 15 Oct 06:00: its last occurrence is generated once', async () => {
        // Created on 15 Sep 00:30 writer time, ending 15 Oct 00:31: two occurrences.
        pinAt(2026, 9, 15, 0, 30);
        await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 15, 0, 31) });
        await runEngine();
        const before = await ledger();
        const balance = await balanceOf(BANK);

        // Seen from 6 h west, the start reads 14 Sep 18:30 and the end 14 Oct 18:31.
        await moveDeviceEast(-6);
        pinAt(2026, 10, 15, 6, 0);
        await runEngine();
        await runEngine();

        const added = await addedSince(before);
        expect(added.map((r) => [r.day, r.index])).toEqual([['2026-10-14', 1]]);
        expect(await balanceOf(BANK)).toBe(balance - 1000);
    });

    it('V-103 b. a rule written 7 h west (Paris -> Tokyo shape) generates nothing beyond the occurrence fixed when its end was set', async () => {
        // Start 15 Sep 12:00, end 14 Oct 23:30 writer time: one occurrence, 15 Sep.
        pinAt(2026, 9, 15, 12, 0);
        await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 14, 23, 30) });
        await runEngine();
        const before = await ledger();
        expect(days(before)).toEqual(['2026-09-15']);

        // Seen from 7 h east, the start reads 15 Sep 19:00 and the end 15 Oct 06:30.
        await moveDeviceEast(7);
        pinAt(2026, 10, 15, 19, 0);
        await runEngine();

        expect(await addedSince(before)).toEqual([]);
    });
});

describe('V-118 an edit that repairs a missing reference and sets the end (process zone; run under TZ=UTC, Africa/Lagos, America/New_York)', () => {
    /** Audit case 4c: 15 Sep generated on BANK, then BANK gone; on 20 Oct, 15 Oct is pending. */
    async function seedOrphanedRule(): Promise<string> {
        pinAt(2026, 9, 15);
        const id = await createRule({ startDate: new Date() });
        await runEngine();
        await orphanWallet(BANK);
        pinAt(2026, 10, 20);
        return id;
    }

    it('V-118 a. wallet repaired and end set to 16 Oct on 20 Oct: 15 Oct is generated once, on the repaired wallet', async () => {
        const id = await seedOrphanedRule();
        const result = await mountHook();

        const outcome = await editRule(result, await formDto(id, { walletId: OTHER, endDate: localDate(2026, 10, 16) }));
        expect((outcome as Refusal).name).not.toBe('RecurringEndDateEditRefusedError');
        expect((await mockRecurringRepo.getById(id))!.walletId).toBe(OTHER);
        const before = await ledger();
        const balance = await balanceOf(OTHER);

        await runEngine();
        pinAt(2026, 11, 20);
        await runEngine();

        expect((await addedSince(before)).map((r) => [r.day, r.walletId, r.amount])).toEqual([['2026-10-15', OTHER, 1000]]);
        expect(await balanceOf(OTHER)).toBe(balance - 1000);
    });

    it('V-118 b. wallet repaired and end set to 10 Oct, before the pending 15 Oct: the edit is refused, names the wallet and 15 Oct, and nothing is saved', async () => {
        const id = await seedOrphanedRule();
        const stored = await mockRecurringRepo.getById(id);
        const before = await ledger();
        const result = await mountHook();

        const outcome = (await editRule(result, await formDto(id, { walletId: OTHER, endDate: localDate(2026, 10, 10) }))) as Refusal;

        expect(outcome.name).toBe('RecurringEndDateEditRefusedError');
        expect(outcome.missing).toEqual(['wallet']);
        expect(outcome.dueDates?.map(ymd)).toEqual(['2026-10-15']);
        expect(await mockRecurringRepo.getById(id)).toEqual(stored);
        expect(await addedSince(before)).toEqual([]);
    });

    it('V-118 c. an ended rule with its wallet gone and 15 Oct pending, repaired and reopened in one edit on 20 Dec: the edit is refused, names the wallet and 15 Oct, and nothing is saved', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();
        await orphanWallet(BANK);
        pinAt(2026, 10, 20, 10, 0);
        await engine();

        pinAt(2026, 12, 20, 10, 0);
        const stored = await mockRecurringRepo.getById(id);
        const before = await ledger();
        const result = await mountHook();

        const outcome = (await editRule(result, await formDto(id, { walletId: OTHER, endDate: null }))) as Refusal;

        expect(outcome.name).toBe('RecurringEndDateEditRefusedError');
        expect(outcome.missing).toEqual(['wallet']);
        expect(outcome.dueDates?.map(ymd)).toEqual(['2026-10-15']);
        expect(await mockRecurringRepo.getById(id)).toEqual(stored);
        expect(await addedSince(before)).toEqual([]);
    });
});

describe('Decision 4 reopening an ended rule catches nothing up (process zone; run under TZ=UTC, Africa/Lagos, America/New_York)', () => {
    /** Audit case 4d: monthly from 15 Sep, ended 19 Oct; the launch on 20 Oct. */
    async function seedEndedRule(): Promise<string> {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();
        pinAt(2026, 10, 20, 10, 0);
        await runEngine();
        return id;
    }

    it('Decision 4 a. end cleared on 20 Dec: nothing for 15 Nov or 15 Dec, and the next occurrence is 15 Jan', async () => {
        const id = await seedEndedRule();

        pinAt(2026, 12, 20, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { endDate: null }));
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);

        pinAt(2027, 1, 15, 10, 0);
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2027-01-15']);
    });

    it('Decision 4 b. end cleared on 15 Dec, a due day: nothing for 15 Nov, and 15 Dec is generated once', async () => {
        const id = await seedEndedRule();

        pinAt(2026, 12, 15, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { endDate: null }));
        await runEngine();
        await runEngine();

        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2026-12-15']);
    });

    it('Decision 4 c. the path the V-118 c refusal names: repair keeping the end, then reopen: 15 Oct on the repaired wallet, nothing for 15 Nov or 15 Dec', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();
        await orphanWallet(BANK);

        pinAt(2026, 12, 20, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { walletId: OTHER }));
        await editRule(result, await formDto(id, { endDate: null }));
        await runEngine();

        expect((await ledger()).map((r) => [r.day, r.walletId])).toEqual([
            ['2026-09-15', BANK],
            ['2026-10-15', OTHER],
        ]);

        pinAt(2027, 1, 15, 10, 0);
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2027-01-15']);
    });
});

describe('controls: end-date behaviour that does not change (process zone; run under TZ=UTC, Africa/Lagos, America/New_York)', () => {
    it('control: an occurrence on the end day is generated on that day', async () => {
        pinAt(2026, 9, 15, 10, 0);
        // Ends at 08:00 on 15 Oct, before the 10:00 of the start: the day counts, not the time.
        await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 15, 8, 0) });
        await runEngine();

        pinAt(2026, 10, 15, 20, 0);
        await runEngine();

        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);
    });

    it('control: a rule with no end keeps generating every month', async () => {
        pinAt(2026, 9, 15, 10, 0);
        await createRule({ startDate: new Date() });
        await runEngine();

        pinAt(2026, 12, 20, 10, 0);
        await runEngine();

        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2026-11-15', '2026-12-15']);
    });

    it('control: audit case 4e, end moved on 20 Oct to 10 Oct while 15 Oct is due: 15 Oct is generated first, then the rule is Ended', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date() });
        await runEngine();

        pinAt(2026, 10, 20, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { endDate: localDate(2026, 10, 10, 10, 0) }));
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);
        expect(await storedStatus(id)).toBe(RecurringRuleStatus.EXPIRED);

        pinAt(2026, 11, 20, 10, 0);
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);
    });

    it('control: a rule with an end, paused on 20 Oct with 15 Oct due and resumed on 20 Dec: 15 Oct first, nothing from the paused period, then 15 Jan', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2027, 3, 31) });
        await runEngine();

        pinAt(2026, 10, 20, 10, 0);
        const result = await mountHook();
        let outcome: { unrecorded: Date[] } | undefined;
        await act(async () => {
            outcome = await result.current.pauseRule(id);
        });
        expect(outcome?.unrecorded).toEqual([]);

        pinAt(2026, 12, 20, 10, 0);
        await act(async () => {
            await result.current.resumeRule(id);
        });
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);

        pinAt(2027, 1, 15, 10, 0);
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2027-01-15']);
    });

    it('control: monthly -> weekly edit on 20 Oct of a rule ending 30 Nov: the weekly dates strictly after 20 Oct up to 30 Nov, then nothing', async () => {
        // 15 Sep 2026 is a Tuesday: the weekly dates are 20 Oct, 27 Oct, 3 Nov...
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 11, 30) });
        await runEngine();

        pinAt(2026, 10, 20, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { frequency: RecurrenceFrequency.WEEKLY }));
        const before = await ledger();
        expect(days(before)).toEqual(['2026-09-15', '2026-10-15']);

        // A launch on the end day, then one after it.
        pinAt(2026, 11, 30, 10, 0);
        await runEngine();
        pinAt(2026, 12, 20, 10, 0);
        await runEngine();

        expect(days(await addedSince(before))).toEqual(['2026-10-27', '2026-11-03', '2026-11-10', '2026-11-17', '2026-11-24']);
    });

    it('control: monthly -> weekly edit that also clears the end of a rule ended 19 Oct, made on 27 Oct, a weekly date: the new schedule starts strictly after 27 Oct (Owner answer, 01/10)', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 19, 10, 0) });
        await runEngine();

        pinAt(2026, 10, 27, 10, 0);
        const result = await mountHook();
        await editRule(result, await formDto(id, { frequency: RecurrenceFrequency.WEEKLY, endDate: null }));
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);

        pinAt(2026, 11, 3, 10, 0);
        await runEngine();
        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15', '2026-11-03']);
    });

    it('control: a rule that generated everything up to an end that has passed is Ended', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 16) });
        await runEngine();
        pinAt(2026, 10, 15, 10, 0);
        await runEngine();

        pinAt(2026, 10, 20, 10, 0);
        expect(await storedStatus(id)).toBe(RecurringRuleStatus.EXPIRED);
    });

    it('control: a rule that generated its last occurrence but whose end is still ahead stays Active', async () => {
        pinAt(2026, 9, 15, 10, 0);
        const id = await createRule({ startDate: new Date(), endDate: localDate(2026, 10, 30) });
        await runEngine();
        pinAt(2026, 10, 20, 10, 0);
        await runEngine();

        expect(days(await ledger())).toEqual(['2026-09-15', '2026-10-15']);
        expect(await storedStatus(id)).toBe(RecurringRuleStatus.ACTIVE);
    });
});
